### ISSUE TITLE
Prime numbers

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-intro-mahagadorn#2]
You asked for a bit of help with the prime number question, so I thought I'd help out here.

Let me write out in "pseudo-code" what you need to do. What I want you to do is go through this and then fill-in the real code. Hopefully it will help you understand what's going on a bit better.

```
prime <- function(x){
    loop start: potential.factor (index) in (x-1):2 (range):
        store remainder of x divided by potential.factor
        if the remainder is 0:
            return FALSE
    loop end
    return TRUE
}
```

I write out pseudo-code like this every time I'm starting out with something difficult, and find it really helps me figure out what's going on. Give this a go, and if you're still stuck in ~ten minutes send me a message in this issue and I'll quickly set up a thing for us to talk.

Sweating a bit on your first exercises is perfectly normal, and I'm impressed that you're being so dedicated. Keep up the good work - you are going to get there!!!

**Comment by mahagadorn** [comment]
Hi Will,

I got that to work. I will try to write a pseudo-code from now on.

Thank you for your help.  I will keep trucking along.

Mallory

**Comment by willpearse** [comment]
That's fine. Please don't be afraid to schedule a session though, and do ask questions when you have them!
