### ISSUE TITLE
Gompert function with loop

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-intro-mahagadorn#4]
```
GompFun <- function (a,b,c,n.timesteps) {
    #Allocate colour and population vector
    pop_vector <- numeric(n.timesteps)
    colour <- rep("black", n.timesteps)

    #Begin loop
    for (i in 1:n.timesteps) {
        #Fill this bit in
        pop_vector[i] <- func_from_q_6(a, b, c)
        #Once you see this example, you'll probably see what I meant with my "hint"
        if(pop_vector[i] > a)
            colour[i] <- "blue"
    }
    plot(pop_vector ~ 1:n.timesteps, col = colour)
}
```

...this is the sort of thing you want to be doing

**Comment by mahagadorn** [comment]
Hi again Will,

I have what may be a stupid question. @AlexRego and I were discussing this the Gompertz function and how "a" is an asymptote; therefore, can the population can never be that "a"?  So, I guess my question is why did we build it into the function to make data points > "a" blue when they can never be greater than "a"?

Thanks for your time,
Mallory

**Comment by willpearse** [comment]
Congratulations! You're the first two students to notice something I wanted people to take from this exercise :D

Sometimes you run your code and the result you get isn't what you expected. More often than not, this is because your code doesn't work, but sometimes it's because what you're asking the computer to do is impossible, or not well-thought-through. This is one of those cases :D Well done!

**Comment by mahagadorn** [comment]
Awesome! Thanks for the help.
