### ISSUE TITLE
Lost professor

### ISSUE THREAD

**Issue by Wolflab** [pearselab/r-intro-mahagadorn#8]
Mallory - yes that issue title has multiple meanings. I had my Q14 working to track the lost professor in the desert. But I was only able to plot distance from origin (which could be useful). I took a peek at yours and see that you figured out how to plot position in space. Awesome. I had to plagiarize some of your ideas. Thanks......Paul

**Comment by mahagadorn** [comment]
HAHAHA! I love that. The more I work with things the more comfortable I get, but I am still having some issues with recognizing when I should and shouldn't use a for loop. 

Glad my code helped.
